[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer"]

[phases.install]
cmds = ["cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
