[phases.setup]
nixPkgs = ["nodejs", "php82"]

[phases.install]
cmds = ["npm ci --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
